#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-CSV-Encoded
Version  : 0.25
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/Z/ZA/ZARQUON/Text-CSV-Encoded-0.25.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZA/ZARQUON/Text-CSV-Encoded-0.25.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-csv-encoded-perl/libtext-csv-encoded-perl_0.25-2.debian.tar.xz
Summary  : 'Encoding aware Text::CSV.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-CSV-Encoded-license
Requires: perl-Text-CSV-Encoded-man
Requires: perl(Text::CSV)
BuildRequires : perl(Text::CSV)

%description
=pod
=head1 NAME
Text::CSV::Encoded - Encoding aware Text::CSV.
=head1 SYNOPSIS
# Here in Perl 5.8 or later
$csv = Text::CSV::Encoded->new ({
encoding_in  => "iso-8859-1", # the encoding comes into   Perl
encoding_out => "cp1252",     # the encoding comes out of Perl
});

%package license
Summary: license components for the perl-Text-CSV-Encoded package.
Group: Default

%description license
license components for the perl-Text-CSV-Encoded package.


%package man
Summary: man components for the perl-Text-CSV-Encoded package.
Group: Default

%description man
man components for the perl-Text-CSV-Encoded package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Text-CSV-Encoded-0.25
mkdir -p %{_topdir}/BUILD/Text-CSV-Encoded-0.25/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Text-CSV-Encoded-0.25/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-CSV-Encoded
cp LICENSE %{buildroot}/usr/share/doc/perl-Text-CSV-Encoded/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/CSV/Encoded.pm
/usr/lib/perl5/site_perl/5.26.1/Text/CSV/Encoded/Coder/Base.pm
/usr/lib/perl5/site_perl/5.26.1/Text/CSV/Encoded/Coder/Encode.pm
/usr/lib/perl5/site_perl/5.26.1/Text/CSV/Encoded/Coder/EncodeGuess.pm
/usr/lib/perl5/site_perl/5.26.1/Text/CSV/README.pod

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Text-CSV-Encoded/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Text::CSV::Encoded.3
/usr/share/man/man3/Text::CSV::Encoded::Coder::Base.3
/usr/share/man/man3/Text::CSV::Encoded::Coder::Encode.3
/usr/share/man/man3/Text::CSV::Encoded::Coder::EncodeGuess.3
